name: '@playwright/test Workflow Template'

on:
  workflow_call:
    inputs:
      url:
        required: false
        type: string
      setup_ruby:
        required: false
        type: boolean

jobs:
    playwright:
        timeout-minutes: 30
        runs-on: ubuntu-latest
        steps:
        - uses: actions/checkout@v6
        - uses: ruby/setup-ruby@v1
          if: ${{ inputs.setup_ruby }}
          with:
            bundler-cache: true
        - uses: actions/setup-node@v6
          with:
            node-version: lts/*
        - name: Install dependencies
          run: npm ci
        - name: Install Playwright Browsers
          run: npx playwright install --with-deps
        - name: Run Playwright tests (deployed)
          if: ${{ inputs.url }}
          run: npx playwright test -c playwright.config.ts
          env:
            URL: ${{ inputs.url }}
        - name: Run Playwright tests (localhost)
          if: ${{ !inputs.url }}
          run: npx playwright test -c playwright.serve.config.ts
        - uses: actions/upload-artifact@v6
          if: ${{ !cancelled() }}
          with:
            name: playwright-report
            path: playwright-report/
            retention-days: 30
